version: '3.2'
    
services:
  python:
    image: opencv_test/python:1.0
    build: ./python
    container_name: 'openCVTest'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ../python:/tmp/work